apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "playground.elasticsearch" . }}-deployment
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  selector:
    matchLabels:
      {{- include "playground.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "playground.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          name: elasticsearch
          env:
            - name: xpack.security.enabled
              value: {{ .Values.elasticsearch.env.expackSecurityEnabled | quote }}
            - name: discovery.type
              value: {{ .Values.elasticsearch.env.discoveryType | quote }}
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
            requests:
              cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
          ports:
            {{- range .Values.elasticsearch.ports }}
            - containerPort: {{ . }}
            {{- end }}