apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground.elasticsearch-svc" . }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.elasticsearch.service.name }}
      port: {{ .Values.elasticsearch.service.port }}
  selector:
    {{- include "playground.selectorLabels" . | nindent 4 }}