apiVersion: v1
kind: Service
metadata:
  name: {{ template "playground.elasticsearch-svc" . }}
  labels:
    app: {{ template "playground.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.elasticsearch.service.name }}
      port: {{ .Values.elasticsearch.service.port }}
  selector:
    app: {{ template "playground.fullname" . }}