apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground.kibana-svc" . }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.kibana.service.name }}
      port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.targetPort }}
  selector:
    {{- include "playground.selectorLabels" . | nindent 4 }}