apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - image: kafka-producer
          name: kafka-producer
          env:
            - name: bootstrap_servers
              value: 'kafka:29092'
            - name: files_dir
              value: '/src/main/resources/twitter'
            - name: fname_file
              value: 'firstname.txt'
            - name: lname_file
              value: 'surname.txt'
            - name: words_file
              value: 'words.txt'