apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: LoadBalancer
  ports:
    - name: elasticsearch
      port: 9200
  selector:
    app: elasticsearch