apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
    - name: kibana
      port: 80
      targetPort: 5601
  selector:
    app: kibana