apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - image: kafka-consumer
          name: kafka-consumer
          imagePullPolicy: Never
          env:
            - name: bootstrap_servers
              value: 'kafka:29092'
            - name: elasticsearch_url
              value: 'elasticsearch:9200'
            - name: elasticsearch_bulk_endpoint
              value: '/kafka_data/_doc/_bulk'
            - name: auto_offset_reset
              value: 'latest'
            - name: group_id
              value: 'consumer-group'
            - name: topic_name
              value: "our_kafka_topic"
